CoreDemo/Areas/Admin/Models/Writer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreDemo.Areas.Admin.Models
{
    public class Writer
    {
        public int ID { get; set; }
        public string Name { get; set; }
    }
}

CoreDemo/Areas/Admin/Controllers/WriterController.cs
using CoreDemo.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreDemo.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class WriterController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult WriterList()
        {
            var jsonWriters = JsonConvert.SerializeObject(writers);
            
            return Json(jsonWriters);
        }
        public IActionResult GetWriterByID(int controllerInId)
        {
            var findWriter = writers.FirstOrDefault(x=>x.ID==controllerInId);
            var jsonWriters = JsonConvert.SerializeObject(findWriter);
            return Json(jsonWriters);
        }
        [HttpPost]
        public IActionResult AddWriter(Writer w)
        {
            writers.Add(w);
            var jsonWriters = JsonConvert.SerializeObject(w);
            return Json(jsonWriters);
        }
        public IActionResult DeleteWriter(int id)
        {
            var writer = writers.FirstOrDefault(x=>x.ID==id);
            writers.Remove(writer);
            return Json(writer);
        }
        public IActionResult UpdateWriter(Writer w)
        {
            var writer = writers.FirstOrDefault(x => x.ID == w.ID);
            writer.Name = w.Name;
            var jsonWriter = JsonConvert.SerializeObject(w);
            return Json(jsonWriter);
        }
        public static List<Writer> writers = new List<Writer>
        {
            new Writer
            {
                ID=1,
                Name="Ayse"
            },
            new Writer
            {
                ID=2,
                Name="Ferhat"
            },
            new Writer
            {
                ID=3,
                Name="Buse"
            },
        };
    }
}

CoreDemo/Controllers/WriterController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using CoreDemo.Models;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace CoreDemo.Controllers
{
    public class WriterController : Controller
    {
        WriterManager writerManager = new WriterManager(new EfWriterRepository());

        private readonly UserManager<AppUser> _userManager;

        public WriterController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }

        [Authorize]
        public IActionResult Index()
        {
            var usermail = User.Identity.Name;
            ViewBag.v = usermail;
            Context c = new Context();
            var writerName = c.Writers.Where(x => x.WriterMail == usermail).Select(y => y.WriterName).FirstOrDefault();
            ViewBag.v1 = writerName;
            return View();
        }
        public IActionResult WriterProfile()
        {
            return View();
        }
        [AllowAnonymous]
        public IActionResult Test()
        {
            return View();
        }
        [AllowAnonymous]
        public PartialViewResult WriterNavbarPartial()
        {
            return PartialView();
        }
        [AllowAnonymous]
        public PartialViewResult WriterFooterPartial()
        {
            return PartialView();
        }
        [HttpGet]
        public async Task<IActionResult> WriterEditProfile()
        {
            var values = await _userManager.FindByNameAsync(User.Identity.Name);//sisteme giriş yapılan kullanıcı adı
            UserUpdateViewModel model = new UserUpdateViewModel();
            model.mail = values.Email;
            model.namesurname = values.NameSurname;
            model.imageurl = values.ImageUrl;
            model.username = values.UserName;
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> WriterEditProfile(UserUpdateViewModel model)
        {
            //validation ekle
            var values = await _userManager.FindByNameAsync(User.Identity.Name);
            values.NameSurname = model.namesurname;
            values.ImageUrl = model.imageurl;
            values.Email = model.mail;
            values.UserName = model.username;
            values.PasswordHash = _userManager.PasswordHasher.HashPassword(values,model.password);
            var result = await _userManager.UpdateAsync(values);
            if (result.Succeeded)
            {
                await HttpContext.SignOutAsync();
                return RedirectToAction("Index", "Login");
                
            }
            else
            {
                return View();
            }
        }
        [AllowAnonymous]
        [HttpGet]
        public IActionResult WriterAdd()
        {
            return View();
        }
        [AllowAnonymous]
        [HttpPost]
        public IActionResult WriterAdd(AddProfileImage p)
        {
            Writer w = new Writer();
            if (p.WriterImage != null)
            {
                var extension = Path.GetExtension(p.WriterImage.FileName);
                var newImageName = Guid.NewGuid() + extension;
                var location = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/WriterImageFiles/", newImageName);
                var stream = new FileStream(location, FileMode.Create);
                p.WriterImage.CopyTo(stream);
                w.WriterImage = newImageName;
            }
            w.WriterMail = p.WriterMail;
            w.WriterName = p.WriterName;
            w.WriterPassword = p.WriterPassword;
            w.WriterStatus = true;
            w.WriterAbout = p.WriterAbout;
            writerManager.TAdd(w);
            return RedirectToAction("Index", "Dashboard");
        }
    }
}

CoreDemo/Views/Writer/Index.cshtml
@{
    Layout = null;
}

<h1>Yazar Paneli</h1>
<br />
<h1>@ViewBag.v</h1>
<br />
<h1>Hoşgeldin @ViewBag.v1</h1>

CoreDemo/Views/Writer/Test.cshtml
@{
    ViewData["Title"] = "Test";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<h1>test</h1>

CoreDemo/Views/Writer/WriterAdd.cshtml
@model CoreDemo.Models.AddProfileImage
@{
    ViewData["Title"] = "WriterAdd";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<form class="form-group" method="post" enctype="multipart/form-data">
    @using (Html.BeginForm("WriterEditProfile", "Writer", FormMethod.Post))
    {
        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Yazar Profil Bilgileri Düzenleme</h4>
                    <input type="hidden" class="form-control" id="exampleInputName1" asp-for="WriteID" placeholder="WriterID">
                    <br />
                    <div class="forms-sample">
                        <div class="form-group">
                            <label for="exampleInputName1">Yazar Ad Soyad</label>
                            <input type="text" class="form-control" id="exampleInputName1" asp-for="WriterName" placeholder="Name">
                            @Html.ValidationMessageFor(x => x.WriterName)
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail3">Mail Adresi</label>
                            <input type="email" class="form-control" id="exampleInputEmail3" asp-for="WriterMail" placeholder="Email">
                            @Html.ValidationMessageFor(x => x.WriterMail)

                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword4">Şifre</label>
                            <input type="password" class="form-control" id="exampleInputPassword4" asp-for="WriterPassword" placeholder="Şifre">
                            @Html.ValidationMessageFor(x => x.WriterPassword)
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword4">Şifre Tekrar</label>
                            <input type="password" class="form-control" id="exampleInputPassword4" asp-for="WriterPasswordAgain" placeholder="Şifre Tekrar">
                            @Html.ValidationMessageFor(x => x.WriterPasswordAgain)
                        </div>
                        <div class="form-group">
                            <label>Yazar Görsel</label>
                            <input type="file" name="WriterImage">
                        </div>
                        <div class="form-group">
                            <label for="exampleTextarea1">Yazar Hakkında</label>
                            <textarea class="form-control" id="exampleTextarea1" asp-for="WriterAbout" rows="4"></textarea>
                        </div>
                        <button type="submit" class="btn btn-gradient-primary mr-2">Kaydet</button>
                        <button class="btn btn-light">İptal</button>
                    </div>
                </div>
            </div>
        </div>
    }
</form>

CoreDemo/Views/Writer/WriterEditProfile.cshtml
@model UserUpdateViewModel
@{
    ViewData["Title"] = "WriterEditProfile";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}


    <div class="col-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Yazar Profil Bilgileri Düzenleme</h4>
                <br />
                <form class="forms-sample" method="post">
                    <div class="form-group">
                        <label for="exampleInputName1">Yazar Ad Soyad</label>
                        <input type="text" class="form-control" asp-for="@Model.namesurname" placeholder="Name">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail3">Kullanıcı Adı</label>
                        <input type="text" class="form-control" asp-for="@Model.username" placeholder="Kullanıcı Adı">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail3">Mail Adresi</label>
                        <input type="email" class="form-control" asp-for="@Model.mail" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail3">Yeni Şifre</label>
                        <input type="text" class="form-control" asp-for="@Model.password" placeholder="Email">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail3">resim yolu</label>
                        <input type="text" class="form-control" asp-for="@Model.imageurl" placeholder="Resim Yolu">
                    </div>
                    <button type="submit" class="btn btn-gradient-primary mr-2">Güncelle</button>
                    <button class="btn btn-light">İptal</button>
                </form>
            </div>
        </div>
    </div>

CoreDemo/Views/Writer/WriterFooterPartial.cshtml
<footer class="footer">
    <div class="container-fluid clearfix">
        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © Tüm Hakları Saklıdır | @DateTime.Now.Year</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Yazar Paneli <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Core 5.0 Proje Kampı </a></span>
    </div>
</footer>

CoreDemo/Views/Writer/WriterNavbarPartial.cshtml
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item nav-profile">
            <a href="#" class="nav-link">
                <div class="nav-profile-image">
                    <img src="~/writer/assets/images/faces/face1.jpg" alt="profile">
                    <span class="login-status online"></span>
                    <!--change to offline or busy as needed-->
                </div>
                <div class="nav-profile-text d-flex flex-column">
                    <span class="font-weight-bold mb-2">Hoşgeldin Murat</span>
                    <span class="text-secondary text-small">Core 5.0 Yazar Paneli</span>
                </div>
                <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Dashboard/Index/">
                <span class="menu-title">Dashboard</span>
                <i class="mdi mdi-home menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/writer/WriterEditProfile/">
                <span class="menu-title">Profilim</span>
                <i class="mdi mdi-contacts menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Blog/BlogListByWriter/">
                <span class="menu-title">Bloglarım</span>
                <i class="mdi mdi-format-list-bulleted menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Blog/BlogAdd/">
                <span class="menu-title">Yeni Blog</span>
                <i class="mdi mdi-open-in-new menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Message/InBox/">
                <span class="menu-title">Gelen Mesajlar</span>
                <i class="mdi mdi-message menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Message/SendBox/">
                <span class="menu-title">Giden Mesajlar</span>
                <i class="mdi mdi-message-plus menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Notification/AllNotification/">
                <span class="menu-title">Bildirimler</span>
                <i class="mdi mdi-call-split menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Blog/Index/">
                <span class="menu-title">Siteye Git</span>
                <i class="mdi mdi-car menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/writer/WriterEditProfile/">
                <span class="menu-title">Ayarlar</span>
                <i class="mdi mdi-settings menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Login/LogOut/">
                <span class="menu-title">Çıkış Yap</span>
                <i class="mdi mdi-exit-to-app menu-icon"></i>
            </a>
        </li>
    </ul>
</nav>